### ISSUE TITLE
Partnership

### ISSUE THREAD

**Issue by OtterUniversityAdmin** [OtterUniversity/DeJayboat#5]
Hi otters, can we partner together as I have created the official OtterUniversity twitter. you guys will post the twitter handle as a watermark in the datamine posts and I will give you shout out on twitter

**Comment by OtterUniversityAdmin** [comment]
@justsomederpystuff @ThaTiemsz @advaith1 give invite to OtterUniversity

**Comment by OtterUniversityAdmin** [comment]
we can support each other

**Comment by OtterUniversityAdmin** [comment]
Your datamine will get more members and my twitter will get more followers

**Comment by Commandtechno** [comment]
real

**Comment by DeJayDev** [comment]
Impersonation is wrong and will get you in trouble on and off GitHub.

As the organization owner, please reach out to me on Discord `DeJay#1337` as this is not the place to have this conversation.
